### ISSUE TITLE
Heroku 構築

### ISSUE THREAD

**Issue by yuta17** [AstarMarket/AstarMarket#31]

**Comment by y-temp4** [comment]
Vercel では GitHub Organizations のリポジトリを使うのが難しそうなので、Heroku を使うことに。

> 機能的には特に感じていませんが、強いて言うなら価格でしょうか。
GitHub Organizations のリポジトリからのデプロイはteamプランへの加入が必要で、こちらが$20/month per member となかなかのお値段、、、
組織での利用は継続的なプロジェクトでなければなかなか厳しいかもしれません。

参考：[Vercelが便利だった｜Hiroki Kodama｜note](https://note.com/hrkd/n/n139cf8e6f3be)
